name: Update Repository Traffic Data

on:
  schedule:
    # Run every 6 hours (at 00:00, 06:00, 12:00, and 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  update-traffic-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout KiCAD Symbols Generator repository
      uses: actions/checkout@v4
      with:
        path: kicad-repo
    
    - name: Download CSV files from clones_monitor repository
      env:
        GH_TOKEN: ${{ secrets.TRAFIC_UPDATE_TOKEN }}
      run: |
        # Fetch clones_history.csv
        gh api \
          -H "Accept: application/vnd.github.v3.raw" \
          /repos/ionutms/clones_monitor/contents/clones_history.csv \
          > kicad-repo/clones_history.csv
        
        # Fetch visitors_history.csv
        gh api \
          -H "Accept: application/vnd.github.v3.raw" \
          /repos/ionutms/clones_monitor/contents/visitors_history.csv \
          > kicad-repo/visitors_history.csv
    
    - name: Commit and push traffic data
      working-directory: kicad-repo
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email '<>'
        
        # Stage both CSV files
        git add clones_history.csv visitors_history.csv
        
        # Check if there are any changes to commit
        if [[ -n $(git status -s) ]]; then
          git commit -m "Update clone and visitor statistics for $(date -u +"%Y-%m-%d %H:%M:%S")"
          git pull --rebase origin main
          git push origin main
        else
          echo "No new traffic data to update"
        fi