name: Update Repository Traffic Data

on:
  schedule:
    # Run every 6 hours (at 00:00, 06:00, 12:00, and 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  update-traffic-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout KiCAD Symbols Generator repository
      uses: actions/checkout@v4
      with:
        path: kicad-repo
    
    - name: Checkout clones_monitor repository
      uses: actions/checkout@v4
      with:
        repository: ionutms/clones_monitor
        path: clones_monitor
    
    - name: Update Repository Traffic Data
      run: |
        # Change to the KiCAD repository directory
        cd kicad-repo
        
        # Copy CSV files from clones_monitor repository
        cp ../clones_monitor/clones_history.csv clones_history.csv
        cp ../clones_monitor/visitors_history.csv visitors_history.csv
    
    - name: Commit and push traffic data
      working-directory: kicad-repo
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email '<>'
        
        # Stage both CSV files
        git add clones_history.csv visitors_history.csv
        
        # Check if there are any changes to commit
        if [[ -n $(git status -s) ]]; then
          git commit -m "Update clone and visitor statistics for $(date -u +"%Y-%m-%d %H:%M:%S")"
          git pull --rebase origin main
          git push origin main
        else
          echo "No new traffic data to update"
        fi